version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn build

artifacts:
  files:
    - lib/**/*
    - node_modules/**/*
    - package.json
